//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContributorProfile
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string Skills { get; set; }
        public string Website { get; set; }
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Institution_Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Experience { get; set; }
        public string Current_Position { get; set; }
    }
}
