//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Job_Master
    {
        public int JobID { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> Course { get; set; }
        public string Designation { get; set; }
        public string Company_Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        [DataType(DataType.MultilineText)]
        public string Location { get; set; }
        public Nullable<System.DateTime> CraetedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Semester { get; set; }
    
        public virtual Course_master Course_master { get; set; }
    }
}
