//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ireadytodayEntities2 : DbContext
    {
        public ireadytodayEntities2()
            : base("name=ireadytodayEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ContributorProfile> ContributorProfiles { get; set; }
        public virtual DbSet<Course_master> Course_master { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Job_Master> Job_Master { get; set; }
        public virtual DbSet<MailTemplateMaster> MailTemplateMasters { get; set; }
        public virtual DbSet<PriceMaster> PriceMasters { get; set; }
        public virtual DbSet<Question_details> Question_details { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Semester_master> Semester_master { get; set; }
        public virtual DbSet<Smstemplate_master> Smstemplate_master { get; set; }
        public virtual DbSet<Stu_Additionalquestionrequest> Stu_Additionalquestionrequest { get; set; }
        public virtual DbSet<Stu_AddQuestionReq> Stu_AddQuestionReq { get; set; }
        public virtual DbSet<StudentReview> StudentReviews { get; set; }
        public virtual DbSet<studentsyllabu> studentsyllabus { get; set; }
        public virtual DbSet<StudyMaterial> StudyMaterials { get; set; }
        public virtual DbSet<Subject_Master> Subject_Master { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<UnitMaster> UnitMasters { get; set; }
        public virtual DbSet<YearMaster> YearMasters { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<TechCours> TechCourses { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<StarRating> StarRatings { get; set; }
        public virtual DbSet<Stu_Result> Stu_Result { get; set; }
        public virtual DbSet<StudentCourseRating> StudentCourseRatings { get; set; }
        public virtual DbSet<StudentProfile> StudentProfiles { get; set; }
    }
}
