//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_details
    {
        public int quizid { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<int> Q_no { get; set; }
        public string Question_Name { get; set; }
        public string Q_op1 { get; set; }
        public string Q_op2 { get; set; }
        public string Q_op3 { get; set; }
        public string Q_op4 { get; set; }
        public string Q_Ans { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Course_master Course_master { get; set; }
        public virtual Subject_Master Subject_Master { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
