//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stu_Additionalquestionrequest
    {
        public int ADQID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> Subject { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string QuestionReplay { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<bool> Updated { get; set; }
    
        public virtual Course_master Course_master { get; set; }
        public virtual Semester_master Semester_master { get; set; }
        public virtual YearMaster YearMaster { get; set; }
    }
}
