//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_AddQuestionReq
    {
        public int QuestionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> Sem { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Qestion_Heading { get; set; }
        public string Question_Description { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
        public Nullable<System.DateTime> Question_Date { get; set; }
        public Nullable<System.DateTime> Anwered_Date { get; set; }
        public Nullable<int> ContributerID { get; set; }
    }
}
