//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class StudentProfile
    {
        public int Student_ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Semester { get; set; }
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CollegeName { get; set; }
        public string Image { get; set; }      
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual Course_master Course_master { get; set; }
    }
}
