//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadyonlineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class studentsyllabu
    {
        public int ssid { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string UnitDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Subject_Master Subject_Master { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
